- name: Detect Ubuntu Release
  shell: cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f2 
  register: ubuntu_release
  changed_when: false

- debug: msg="Ubuntu Release {{ubuntu_release.stdout}}"

- name: Check for Supported Ubuntu Version
  assert:
    that: "ubuntu_release.stdout == desired_ubuntu_release"
    msg: "This Playbook is written for Ubuntu version {{desired_ubuntu_release}} but the environment is using version {{ubuntu_release.stdout}}"

- name: Create cumulus user
  user:
    name: cumulus
    groups:
      - sudo
    shell: /bin/bash
    password: $1$8WOBD1pA$uph5ks6BG29F12dt/ORmE0
  tags: create_user

- name: Setup password-less sudo
  copy:
    content: |
      cumulus ALL=(ALL) NOPASSWD:ALL
    dest: /etc/sudoers.d/10_cumulus
  tags: create_user

- name: Create .ssh directory
  file:
    path: /home/cumulus/.ssh
    state: directory
    mode: 0700
    owner: cumulus
    group: cumulus
  tags: create_user

- name: Remove MOTD Restart Warnings
  file:
    path: /etc/update-motd.d/98-reboot-required
    state: absent

- name: Set DHCP to never Timeout
  copy: src=dhclient.conf dest=/etc/dhcp/dhclient.conf

- name: Deploy LLDPD configuration
  copy:
   content: |
     configure lldp portidsubtype ifname
   dest: /etc/lldpd.d/port_info.conf

- name: Restart LLDPd
  service: name=lldpd state=restarted

- name: Install a .deb package
  apt:
    deb: http://ftp.us.debian.org/debian/pool/main/i/ifupdown2/ifupdown2_1.0~git20170314-1_all.deb

- name: Copy Default Bonding Configuration
  copy: src=bond.json dest=/etc/network/ifupdown2/policy.d/bond.json

- name: Set Default Timezone
  copy:
    content: "Etc/UTC"
    dest: /etc/timezone

- name: Apply Timezone
  shell: /usr/sbin/dpkg-reconfigure -f noninteractive tzdata

- name: Copy NTP Configuration
  copy: src=ntp.conf dest=/etc/ntp.conf

- name: Copy DHCP exit hook for setting hostname
  copy: src=dhcp-sethostname dest=/etc/dhcp/dhclient-exit-hooks.d/dhcp-sethostname

- name: Push Interface Config
  copy:
    src: interfaces
    dest: /etc/network/interfaces
